### PR TITLE
Incorporating downstream changes before update

### PR DESCRIPTION
**Pull request by ProgrammerDan**
I think someone said they were updating this but it's been kind of quiet. I guess they rewrote it? So idk. Incorporating 1.12 changes anyway.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by DevotedServant** [comment]
Build finished.

**Comment by ProgrammerDan** [comment]
ok to retest

**Comment by ProgrammerDan** [comment]
retest this please

**Comment by ProgrammerDan** [comment]
retest this please

**Pull request merged**
